routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return redirect()->route('productlist');
});

Route::get('/', 'OrderController@index')->name('productlist');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/itemaddtocart', 'OrderController@itemAddToCart')->name('itemaddtocart');

Route::post('/deletecartitem', 'OrderController@deleteCartItem')->name('deletecartitem')->middleware('auth:web');

Route::get('/admin', function () {
    return redirect()->route('admin.login');
});
Route::post('/bynowproduct', 'OrderController@getByNowProduct')->name('bynowproduct')->middleware('auth:web');
Route::post('/penddingproductorder', 'OrderController@penddingProductOrder')->name('penddingproductorder');

Route::group(['prefix' => 'admin','as'=>'admin.'], function () {
  Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'Admin\Auth\LoginController@login');
  Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');

  Route::get('/register', 'Admin\Auth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'Admin\Auth\RegisterController@register');

  Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm');
  Route::group(['middleware'=>'admin'], function () {
    Route::get('/users', 'Admin\UserController@index');  
    Route::get('/getuserlist', 'Admin\UserController@show')->name('userlist');  
    Route::get('/createuser', 'Admin\UserController@create')->name('createuser'); 
    Route::post('/storeuser', 'Admin\UserController@store')->name('storeuser');  
    Route::get('/edituser/{id}', 'Admin\UserController@edit')->name('edituser');
    Route::post('/updateuser', 'Admin\UserController@update')->name('updateuser');
    Route::post('/deleteuser', 'Admin\UserController@destroy')->name('deleteuser'); 
      
    Route::get('/products', 'Admin\ProductControlle@index');  
    Route::get('/getproductslist', 'Admin\ProductControlle@show')->name('getproductslist');  
    Route::get('/createproduct', 'Admin\ProductControlle@create')->name('createproduct');
    Route::post('/storeproduct', 'Admin\ProductControlle@store')->name('storeproduct'); 
    Route::get('/editproduct/{id}', 'Admin\ProductControlle@edit')->name('editproduct');
    Route::post('/updateproduct', 'Admin\ProductControlle@update')->name('updateproduct');
    Route::post('/deleteproduct', 'Admin\ProductControlle@destroy')->name('deleteproduct');

  });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\User;
use DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.users.add_update');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validatedData = $request->validate([
            'email' => 'required|unique:users,email',
        ]);
        
        try {
          User::create([
            'name'      => $request->name,
            'email'     => $request->email,
            'password'  => Hash::make($request->password)
          ]);
          return redirect('/admin/users')->with('message', 'User successfully added.');
        } catch (\Exception $e) {

            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        if ($request->ajax()) {
            $data = User::select('*');
            return Datatables::of($data)

                ->addColumn('action', function($row){
                    $actionBtn = '<a href="' . route('admin.edituser', encrypt($row->id)) . '" class="edit btn btn-success btn-sm">Edit</a> <a href="javascript:void(0)" onclick="deleteUser('.$row->id.')" class="delete btn btn-danger btn-sm">Delete</a>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $id = decrypt($id);
        // dd($id);
        $data = User::where('id',$id)->first();
       
        return view('admin.users.add_update')->with(['data' => $data]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $validatedData = $request->validate([
            'email' => 'required|unique:users,email,' . $request->edit_id
        ]);
        
        try {

            if($request->password == ''){
                $data       = User::select('password')->where('id',$request->edit_id)->first();
                $password   = $data->password;
            }else{
                $password   = Hash::make($request->password);
            }

          User::where('id',$request->edit_id)->update([
            'name'      => $request->name,
            'email'     => $request->email,
            'password'  => $password,
          ]);
          return redirect('/admin/users')->with('message', 'User successfully updated.');
        } catch (\Exception $e) {

            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        try {
            $data = User::findOrFail($request->id);
            $data->delete();
           return response()->json('success');
        } catch (\Exception $e) {

            return $e->getMessage();
        }
    }
}

resources/views/admin/users/add_update.blade.php
@extends('admin.layout.auth')

@section('content')
<?php
  if(isset($data) && $data != ''){
    $id                 = $data->id;
    $name               = $data->name;
    $email              = $data->email;
  }else{
    $id                 = '0';
    $name               = old('name');
    $email              = old('email');    
  }
?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" id="user-form" action="{{isset($id) && $id != 0 ? route('admin.updateuser') :route('admin.storeuser')}}">
                        @csrf
                        <input type="hidden" name="edit_id" value="{{isset($id)?$id:'0'}}">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input id="name" type="text" class="form-control" name="name" value="{{$name}}">
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" name="email" value="{{$email}}">
                           @if($errors->has('email'))
                                <label  class="error">{{ $errors->first('email') }}</label>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                             <input id="password" type="password" class="form-control" name="password" >
                            
                        </div>
                        <div class="form-group">
                            <label for="password-confirm">Confirm Password</label>
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" >
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Register') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script type="text/javascript">
    $(function () {
        var id = '{{$id}}';

        if(id != 0){
            var pass_rule = false;
        }else{
            var pass_rule = true;
        }

        $("#user-form").validate({
            rules: {
              name: "required",
              email: {
                required: true,
                email: true
              },
              password: {
                required: pass_rule,
                minlength: 6
              },
              password_confirmation: {
                    required: pass_rule,
                    minlength: 6,
                    equalTo: "#password"
              }
            },
            submitHandler: function(form) {
              form.submit();
            }
        });
    });
    
</script>
@endpush

resources/views/admin/users/index.blade.php
@extends('admin.layout.auth')

@section('content')
<div class="container">
    <div class="row">
    	<div class="session-msg">
	    	@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif
    	</div>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"  >
                	<h2 class="pb-2">User List <a href="{{route('admin.createuser')}}" class="btn btn-info" style="float: right; ">Add User</a></h2>
                	
                </div>
                <div class="panel-body">
                    <table id="userlist-tbl" class="table table-bordered yajra-datatable">
				        <thead>
				            <tr>
				                <th>No</th>
				                <th>Name</th>
				                <th>Email</th>
				                <th>Action</th>
				            </tr>
				        </thead>
				        <tbody>
				        </tbody>
				    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script type="text/javascript">
$(function () {
	iniUserlist();

});
	function iniUserlist() {
		var table = $('#userlist-tbl').DataTable({
        processing: true,
        serverSide: true,
        "order": [[ 0, "desc" ]],
        ajax: "{{ route('admin.userlist') }}",
	        columns: [
	            {data: 'id', name: 'id', "visible": false, searchable: true},
	            {data: 'name', name: 'name'},
	            {data: 'email', name: 'email'},
	            {
	                data: 'action', 
	                name: 'action', 
	                orderable: true, 
	                searchable: true
	            },
	        ]
	    });
	}
	function deleteUser(id) {
		if (confirm("Are you sure delete this user?")) {
	        $.ajax({
            type:'POST',
            url: "{{route('admin.deleteuser')}}",
            dataType:'json',
	            data: {
	              _token:'{{ csrf_token() }}', 
	              id:id
	             },
	            success:function(data){
	            	$('.session-msg').html('<div class="alert alert-success">User successfully Deleted.</div>');
	            	$('#userlist-tbl').DataTable().ajax.reload()
	            },
	        });
	    }
        
    }
</script>
@endpush