routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return redirect()->route('productlist');
});

Route::get('/', 'OrderController@index')->name('productlist');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/itemaddtocart', 'OrderController@itemAddToCart')->name('itemaddtocart');

Route::post('/deletecartitem', 'OrderController@deleteCartItem')->name('deletecartitem')->middleware('auth:web');

Route::get('/admin', function () {
    return redirect()->route('admin.login');
});
Route::post('/bynowproduct', 'OrderController@getByNowProduct')->name('bynowproduct')->middleware('auth:web');
Route::post('/penddingproductorder', 'OrderController@penddingProductOrder')->name('penddingproductorder');

Route::group(['prefix' => 'admin','as'=>'admin.'], function () {
  Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'Admin\Auth\LoginController@login');
  Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');

  Route::get('/register', 'Admin\Auth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'Admin\Auth\RegisterController@register');

  Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm');
  Route::group(['middleware'=>'admin'], function () {
    Route::get('/users', 'Admin\UserController@index');  
    Route::get('/getuserlist', 'Admin\UserController@show')->name('userlist');  
    Route::get('/createuser', 'Admin\UserController@create')->name('createuser'); 
    Route::post('/storeuser', 'Admin\UserController@store')->name('storeuser');  
    Route::get('/edituser/{id}', 'Admin\UserController@edit')->name('edituser');
    Route::post('/updateuser', 'Admin\UserController@update')->name('updateuser');
    Route::post('/deleteuser', 'Admin\UserController@destroy')->name('deleteuser'); 
      
    Route::get('/products', 'Admin\ProductControlle@index');  
    Route::get('/getproductslist', 'Admin\ProductControlle@show')->name('getproductslist');  
    Route::get('/createproduct', 'Admin\ProductControlle@create')->name('createproduct');
    Route::post('/storeproduct', 'Admin\ProductControlle@store')->name('storeproduct'); 
    Route::get('/editproduct/{id}', 'Admin\ProductControlle@edit')->name('editproduct');
    Route::post('/updateproduct', 'Admin\ProductControlle@update')->name('updateproduct');
    Route::post('/deleteproduct', 'Admin\ProductControlle@destroy')->name('deleteproduct');

  });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
   	protected $table = 'products';
   	/**
     * The primary key associated with the table.
     *
     * @var string
     */
    // protected $primaryKey = 'id';


    protected $fillable = [
                'name',
                'description',
                'price',
                'pro_image',
                'quantity'
            ];

    /**
    * The attributes that should be mutated to dates.
    *
    * @var array
    */
}

resources/views/admin/products/add_update.blade.php
@extends('admin.layout.auth')

@section('content')
<?php

if(isset($data->id) && $data->id !=''){
  $id           = $data->id;
  $name         = $data->name;
  $description  = $data->description;
  $pro_img      = $data->pro_image;
  $price        = $data->price;
  $quantity     = $data->quantity;
}else{
  $id           = '0';
  $name        = '';
  $description  = '';
  $pro_img      = '';
  $price        = '';
  $quantity     = '';
}

  if($pro_img!= ''){
    $pro_img =  asset('/images/product')."/".$pro_img;
  }else{
    $pro_img = asset('/images/img')."/image-placeholder.png";
  }

?>
<div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title">Product</h3>
  </div>
  <!-- /.card-header -->
  <!-- form start -->
  <form method="POST" action="{{isset($id) && $id != 0 ? route('admin.updateproduct') :route('admin.storeproduct')}}" id="product-form"  enctype="multipart/form-data" >
    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
    <input type="hidden" name="edit_id" value="{{isset($id)?$id:'0'}}">
    <div class="card-body">
      <div class="row">
        <div class="col-md-6 form-group">
          <label for="name">Name</label>
        <input type="text" name="name" class="form-control" id="name" value="{{$name}}" placeholder="Enter Name">
        </div>
        <div class="col-md-6 form-group">
          <label for="price">Price</label>
        <input type="text" name="price" class="form-control" id="price" value="{{$price}}" placeholder="Enter Title">
        </div>
       
      </div>
      <div class="row">
        <div class="col-md-6 form-group">
          <label for="description">Description</label>
          <textarea id="description" name="description" placeholder="Description" class="form-control" rows="4" cols="50">{{$description}}</textarea>
        </div>
        <div class="col-md-6 form-group">
        <label for="pro_img">Image</label>
          <div class="custom-file">
            <input type="file" class="custom-file-input" name="pro_img" id="pro_img">
            <input type="hidden" class="custom-file-input" value="{{(isset($data->pro_image) && $data->pro_image != '' ? $data->pro_image : '')}}" name="hiddenpro_img" id="hiddenpro_img">
            <label class="custom-file-label" for="pro_img">Choose file</label>
          </div>
          <img id="img_prview" src="{{$pro_img}}" alt="your image" height="100" width="100" />
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 form-group">
          <label for="quantity">Quantity</label>

          <input type="text" class="form-control datepicker" value="{{$quantity}}" placeholder="Quantity" name="quantity" id="quantity">
            
        </div>
      </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      
      reader.onload = function(e) {
        $('#img_prview').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]); // convert to base64 string
    }
  }

  $("#pro_img").change(function() {
    readURL(this);
  });

  $(document).ready(function () {
    $('#product-form').validate({ // initialize the plugin
        rules: {
            name: {
              required: true
            },
            price: {
              required: true
            },
            description: {
                required: true,                
            },
             quantity: {
              required: true,
              digits: true               
            },
            pro_img: {
              // required: true,
              extension: "jpg|jpeg|png"
            }
        }
    });
     $('#price').keypress(function (event) {
            return isNumber(event, this)
        });
  });
    // THE SCRIPT THAT CHECKS IF THE KEY PRESSED IS A NUMERIC OR DECIMAL VALUE.
    function isNumber(evt, element) {

      var charCode = (evt.which) ? evt.which : event.keyCode

      if (
          (charCode != 45 || $(element).val().indexOf('-') != -1) &&      // “-” CHECK MINUS, AND ONLY ONE.
          (charCode != 46 || $(element).val().indexOf('.') != -1) &&      // “.” CHECK DOT, AND ONLY ONE.
          (charCode < 48 || charCode > 57))
          return false;

      return true;
    }  
</script>
@endpush

resources/views/admin/products/index.blade.php
@extends('admin.layout.auth')

@section('content')
<div class="container">
    <div class="row">
    	<div class="session-msg">
	    	@if(session()->has('message'))
			    <div class="alert alert-success">
			        {{ session()->get('message') }}
			    </div>
			@endif
    	</div>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"  >
                	<h2 class="pb-2">Product List <a href="{{route('admin.createproduct')}}" class="btn btn-info" style="float: right; ">Add Product</a></h2>
                </div>
                <div class="panel-body">
                    <table id="productlist-tbl" class="table table-bordered yajra-datatable">
				        <thead>
				            <tr>
				                <th>No</th>
				                <th>Name</th>
				                <th>Image</th>
				                <th>Price ($)</th>
				                <th>Quantity</th>
				                <th>Action</th>
				            </tr>
				        </thead>
				        <tbody>
				        </tbody>
				    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script type="text/javascript">
$(function () {
	iniProductlist();
});
	function iniProductlist() {
		var table = $('#productlist-tbl').DataTable({
        dom: 'lBfrtip',
        "destroy"   : true,
        "processing": true,
        "serverSide": true,
        "searching": true,
        "pageLength": 10,
        "order": [[ 0, "desc" ]],
        ajax: "{{ route('admin.getproductslist') }}",
	        columns: [
	            {data: 'id', name: 'id', "visible": false, searchable: false},
	            {data: 'name', name: 'name'},
	            { "render": 
		              function (data, type, JsonResultRow, meta) 
		              {
		                return '<img src="'+JsonResultRow.pro_image+'" border="0" width="50" height="50" class="img-rounded" align="center">';
		              }, searchable: false
		        },
	            {data: 'price', name: 'price'},
	            {data: 'quantity', name: 'quantity'},
	            {data: 'action',name: 'action',orderable: false,searchable: false},
	        ]
	    });
	}
	function deleteProduct(id) {
		if (confirm("Are you sure delete this Product?")) {
	        $.ajax({
            type:'POST',
            url: "{{route('admin.deleteproduct')}}",
            dataType:'json',
	            data: {
	              _token:'{{ csrf_token() }}', 
	              id:id
	             },
	            success:function(data){
	            	$('.session-msg').html('<div class="alert alert-success">User successfully Deleted.</div>');
	            	$('#productlist-tbl').DataTable().ajax.reload()
	            },
	        });
	    }
        
    }
</script>
@endpush