routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return redirect()->route('productlist');
});

Route::get('/', 'OrderController@index')->name('productlist');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/itemaddtocart', 'OrderController@itemAddToCart')->name('itemaddtocart');

Route::post('/deletecartitem', 'OrderController@deleteCartItem')->name('deletecartitem')->middleware('auth:web');

Route::get('/admin', function () {
    return redirect()->route('admin.login');
});
Route::post('/bynowproduct', 'OrderController@getByNowProduct')->name('bynowproduct')->middleware('auth:web');
Route::post('/penddingproductorder', 'OrderController@penddingProductOrder')->name('penddingproductorder');

Route::group(['prefix' => 'admin','as'=>'admin.'], function () {
  Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'Admin\Auth\LoginController@login');
  Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');

  Route::get('/register', 'Admin\Auth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'Admin\Auth\RegisterController@register');

  Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm');
  Route::group(['middleware'=>'admin'], function () {
    Route::get('/users', 'Admin\UserController@index');  
    Route::get('/getuserlist', 'Admin\UserController@show')->name('userlist');  
    Route::get('/createuser', 'Admin\UserController@create')->name('createuser'); 
    Route::post('/storeuser', 'Admin\UserController@store')->name('storeuser');  
    Route::get('/edituser/{id}', 'Admin\UserController@edit')->name('edituser');
    Route::post('/updateuser', 'Admin\UserController@update')->name('updateuser');
    Route::post('/deleteuser', 'Admin\UserController@destroy')->name('deleteuser'); 
      
    Route::get('/products', 'Admin\ProductControlle@index');  
    Route::get('/getproductslist', 'Admin\ProductControlle@show')->name('getproductslist');  
    Route::get('/createproduct', 'Admin\ProductControlle@create')->name('createproduct');
    Route::post('/storeproduct', 'Admin\ProductControlle@store')->name('storeproduct'); 
    Route::get('/editproduct/{id}', 'Admin\ProductControlle@edit')->name('editproduct');
    Route::post('/updateproduct', 'Admin\ProductControlle@update')->name('updateproduct');
    Route::post('/deleteproduct', 'Admin\ProductControlle@destroy')->name('deleteproduct');

  });
});

resources/views/admin/layout/auth.blade.php
<!doctype html>
<html>
<head>
    @include('admin.layout.header')
    <style type="text/css">
        label.error{
            color: red;
        }
    </style>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

               <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guard('admin')->check())
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/admin/users') }}">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/admin/products') }}">Products</a>
                    </li>
                    <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::guard('admin')->user()->name }} <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('admin.logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/admin/login') }}">Login</a>
                    </li>
                    <!--  -->
                @endif
            </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
    </div>
    <footer class=" text-center">
        @include('admin.layout.footer')
    </footer>

</div>
</body>
</html>

resources/views/admin/layout/footer.blade.php
<div id="copyright text-right">© Copyright 2021 BizTech </div>

 <script src="{{asset('js/jquery.min.js')}}"></script>
 
 <script type="text/javascript" src="{{asset('js/bootstrap.min.js')}}"></script>
 <!-- <script src="{{asset('js/bootstrap-datepicker.min.js')}}"></script> -->
 <script src="{{asset('js/datatables.min.js')}}"></script>
 <script src="{{asset('js/jquery.validate.min.js')}}"></script>
 <script src="{{asset('js/additional-methods.min.js')}}"></script>
  @stack('scripts')

resources/views/admin/layout/header.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Laravel') }}</title>

<!-- Scripts -->

<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

<!-- Styles -->
<link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/datatables.min.css')}}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />


@stack('styles')